name: Update Homebrew Formula

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to update to (e.g., 0.1.0)"
        required: true
        default: "0.1.0"
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Extract version from release
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
            VERSION=${VERSION#v}  # Remove 'v' prefix if present
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Install homebrew-pypi-poet
        run: |
          python -m pip install --upgrade pip
          pip install streamlm==${{ steps.get_version.outputs.version }} homebrew-pypi-poet
      - name: Generate formula
        run: |
          poet -f streamlm > homebrew/Formula/streamlm.rb
      - name: Update formula metadata
        run: |
          python3 -c "
          import re
          content = open('homebrew/Formula/streamlm.rb').read()
          content = re.sub(r'desc \".*?\"', 'desc \"A command-line interface for interacting with various Large Language Models\"', content)
          content = re.sub(r'homepage \".*?\"', 'homepage \"https://github.com/jeffmylife/streamlm\"', content)
          content = re.sub(r'license \".*?\"', 'license \"MIT\"', content)
          content = re.sub(
              r'test do.*?end',
              'test do\\n    assert_match \"streamlm version\", shell_output(\"#{bin}/lm --version\")\\n    assert_match \"Usage:\", shell_output(\"#{bin}/lm --help\")\\n  end',
              content,
              flags=re.DOTALL
          )
          open('homebrew/Formula/streamlm.rb', 'w').write(content)
          "
      - name: Display updated formula
        run: cat homebrew/Formula/streamlm.rb
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add homebrew/Formula/streamlm.rb
          git commit -m "Update Homebrew formula to version ${{ steps.get_version.outputs.version }}" || exit 0
          git push
